# Generated by Django 4.2 on 2023-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='test', max_length=128),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='test', max_length=128),
        ),
    ]
