# Generated by Django 4.2 on 2023-05-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_name_alter_productcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
