# Generated by Django 4.2 on 2023-05-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_basket_user_basket_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
